# Generated by Django 2.2.5 on 2019-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=5)),
                ('img', models.ImageField(upload_to='pics')),
                ('vid', models.FileField(upload_to='vids')),
            ],
        ),
    ]
