# Generated by Django 2.2.5 on 2019-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
