# Generated by Django 2.2.5 on 2019-09-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='vid',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
