# Generated by Django 2.2.5 on 2019-09-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190916_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outimg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='outvid',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
