# Generated by Django 2.2.5 on 2019-10-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190927_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spec',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
